GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/services

###

POST http://localhost:3000/api/services
Content-Type: application/json

{
  "name": "Gold",
  "description": "This is 90 days basic membership",
  "price": 6.99
}

###

### DELETE
DELETE http://localhost:3000/api/services/62625f6b749a6d421f5cc4d5
